# Generated by Django 6.0.1 on 2026-05-11 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(help_text='Η ερώτηση του χρήστη')),
                ('query_hash', models.CharField(db_index=True, help_text='SHA256 hash της ερώτησης για γρήγορη αναζήτηση', max_length=64, unique=True)),
                ('search_results', models.JSONField(default=list, help_text='Αποτελέσματα από web scraping (URLs, titles, snippets)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('times_accessed', models.IntegerField(default=0, help_text='Πόσες φορές έχει ζητηθεί αυτή η ερώτηση')),
            ],
            options={
                'verbose_name': 'Search Query',
                'verbose_name_plural': 'Search Queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['query_hash'], name='chatbot_sea_query_h_cf52c8_idx'), models.Index(fields=['-created_at'], name='chatbot_sea_created_a87ab8_idx')],
            },
        ),
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_text', models.TextField(help_text='Η απάντηση του AI')),
                ('model_used', models.CharField(default='llama3.1:8b', help_text='Ποιο AI model χρησιμοποιήθηκε', max_length=100)),
                ('response_time', models.FloatField(help_text='Χρόνος απάντησης σε δευτερόλεπτα')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_from_cache', models.BooleanField(default=False, help_text='Ήταν cached η απάντηση;')),
                ('search_query', models.ForeignKey(help_text='Σε ποια ερώτηση αντιστοιχεί αυτή η απάντηση', on_delete=django.db.models.deletion.CASCADE, related_name='ai_responses', to='chatbot.searchquery')),
            ],
            options={
                'verbose_name': 'AI Response',
                'verbose_name_plural': 'AI Responses',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WebScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('content', models.TextField(help_text='Το κείμενο που βρέθηκε')),
                ('snippet', models.TextField(blank=True, help_text='Σύντομο απόσπασμα', max_length=500)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('search_query', models.ForeignKey(help_text='Για ποια ερώτηση έγινε το scraping', on_delete=django.db.models.deletion.CASCADE, related_name='scraped_data', to='chatbot.searchquery')),
            ],
            options={
                'verbose_name': 'Web Scraped Data',
                'verbose_name_plural': 'Web Scraped Data',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
